apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: auth-service-credentials
  namespace: auth-service
spec:
  backendType: secretsManager
  data:
    - key: "/dukat/prod/auth-service/JWT_SECRET"
      name: JWT_SECRET
    - key: "/dukat/prod/auth-service/DB_URL"
      name: DATABASE_URL
  template:
    type: Opaque
  refreshInterval: "1h"