global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3010']

  - job_name: 'livekit'
    static_configs:
      - targets: ['livekit:9090']

  - job_name: 'voice-agent'
    static_configs:
      - targets: ['voice-agent:8000']
